server:
  port: 11001
spring:
  application:
    name: auth
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/community_auth
    username: root
    password: lsk123456
    driver-class-name: org.mariadb.jdbc.Driver
common:
  redis:
    host: localhost
    port: 6379
lsk:
  debug:
    enabled: true
logging:
  level:
    com.lsk.community.back.common.authz.holder: DEBUG
    com.lsk.community.back.common.response.holder: DEBUG
