server:
  port: 11002
spring:
  application:
    name: community
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/community_core
    username: root
    password: lsk123456
    driver-class-name: com.mysql.cj.jdbc.Driver
common:
  redis:
    host: localhost
    port: 6379
    database: 2
    password: lsk123456
  debug:
    enabled: true
community:
  work:
    pageSize: 10
mybatis:
  table:
    auto: update
  model:
    pack: com.lsk.community.back.community.model